#!/usr/bin/env python3
"""Exact DESI DR1 LRG x ELG odd-multipole estimator using pycorr/Corrfunc.

This is the production pair-counting replacement for the exploratory
nearest-neighbour Monte-Carlo estimator. It uses all selected pairs in
Corrfunc, supports multiple independent DESI random realizations, and
performs an explicit tracer-order sign-reversal test.

This script measures the data vector only. Statistical significance should
be assessed with a mock covariance generated by running the identical
estimator on a large mock ensemble.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import numpy as np
from astropy.cosmology import FlatLambdaCDM
from astropy.io import fits

from pycorr import TwoPointCorrelationFunction, project_to_poles

LEGACY_COSMO = FlatLambdaCDM(H0=67.4, Om0=0.315, Tcmb0=2.7255)
LEGACY_H = 0.674
_DISTANCE_COSMOLOGY = "desi"
_DESI_COSMO = None


def set_distance_cosmology(name):
    global _DISTANCE_COSMOLOGY, _DESI_COSMO
    name = str(name).lower()
    if name not in {"desi", "legacy_astropy"}:
        raise ValueError(f"Unknown distance cosmology: {name}")
    if name == "desi" and _DESI_COSMO is None:
        try:
            from cosmoprimo.fiducial import TabulatedDESI
        except ImportError as exc:
            raise RuntimeError(
                "DESI fiducial distances require cosmoprimo. Install the pinned Git version from requirements.txt."
            ) from exc
        _DESI_COSMO = TabulatedDESI()
    _DISTANCE_COSMOLOGY = name


def distance_mpc_over_h(z):
    z = np.asarray(z, dtype="f8")
    if _DISTANCE_COSMOLOGY == "desi":
        if _DESI_COSMO is None:
            set_distance_cosmology("desi")
        return np.asarray(_DESI_COSMO.comoving_radial_distance(z), dtype="f8")
    return np.asarray(LEGACY_COSMO.comoving_distance(z).value * LEGACY_H, dtype="f8")


def col(data, *names, default=None):
    available = {name.upper(): name for name in data.names}
    for name in names:
        if name.upper() in available:
            return np.asarray(data[available[name.upper()]])
    if default is not None:
        return default
    raise KeyError(f"Missing columns {names}; available={list(data.names)}")


def read_catalog(paths, zmin, zmax):
    chunks = []
    for filename in paths:
        with fits.open(filename, memmap=True) as hdul:
            data = hdul[1].data
            n = len(data)
            ra = col(data, "RA").astype("f8", copy=False)
            dec = col(data, "DEC").astype("f8", copy=False)
            z = col(data, "Z").astype("f8", copy=False)
            weight = col(data, "WEIGHT", default=np.ones(n)).astype("f8", copy=False)
            weight_fkp = col(data, "WEIGHT_FKP", default=np.ones(n)).astype("f8", copy=False)
            good = (
                np.isfinite(ra) & np.isfinite(dec) & np.isfinite(z)
                & np.isfinite(weight) & np.isfinite(weight_fkp)
                & (weight > 0.0) & (weight_fkp > 0.0)
                & (z >= zmin) & (z < zmax)
            )
            chunks.append(
                (
                    np.asarray(ra[good], dtype="f8"),
                    np.asarray(dec[good], dtype="f8"),
                    np.asarray(z[good], dtype="f8"),
                    np.asarray((weight[good] * weight_fkp[good]), dtype="f8"),
                )
            )
    if not chunks:
        raise RuntimeError("No catalog files supplied")
    return tuple(np.concatenate([chunk[i] for chunk in chunks]) for i in range(4))


def rdd(cat):
    ra, dec, z, _ = cat
    chi = distance_mpc_over_h(z)
    return [ra, dec, chi]


def weights(cat):
    return cat[3]


def weighted_zeff(cat1, cat2):
    z1, w1 = cat1[2], cat1[3]
    z2, w2 = cat2[2], cat2[3]
    return float(0.5 * (np.average(z1, weights=w1) + np.average(z2, weights=w2)))


def run_corr(data1, data2, random1, random2, sedges, nmu, nthreads, theta_min_deg):
    muedges = np.linspace(-1.0 - 1e-7, 1.0 + 1e-7, nmu + 1)
    selection = None
    if theta_min_deg > 0:
        selection = {"theta": (float(theta_min_deg), 180.0)}
    corr = TwoPointCorrelationFunction(
        "smu",
        (sedges, muedges),
        data_positions1=rdd(data1),
        data_positions2=rdd(data2),
        randoms_positions1=rdd(random1),
        randoms_positions2=rdd(random2),
        data_weights1=weights(data1),
        data_weights2=weights(data2),
        randoms_weights1=weights(random1),
        randoms_weights2=weights(random2),
        estimator="landyszalay",
        position_type="rdd",
        los="midpoint",
        selection_attrs=selection,
        engine="corrfunc",
        nthreads=nthreads,
        compute_sepsavg=False,
    )
    sep, poles = project_to_poles(
        corr, ells=(1, 3), return_sep=True, return_cov=False, ignore_nan=False
    )
    poles = np.asarray(poles, dtype="f8")
    if poles.shape[0] != 2:
        raise RuntimeError(f"Unexpected poles shape {poles.shape}")
    return corr, np.asarray(sep, dtype="f8"), poles[0], poles[1]


def finite_or_raise(name, *arrays):
    for arr in arrays:
        if not np.all(np.isfinite(arr)):
            raise RuntimeError(f"Non-finite values in {name}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lrg-data", nargs="+", required=True)
    ap.add_argument("--elg-data", nargs="+", required=True)
    ap.add_argument("--lrg-random", nargs="+", required=True)
    ap.add_argument("--elg-random", nargs="+", required=True)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--zmin", type=float, default=0.80)
    ap.add_argument("--zmax", type=float, default=1.10)
    ap.add_argument("--sep-edges", default="20,40,60,80,100,120,140")
    ap.add_argument("--mu-bins", type=int, default=240)
    ap.add_argument("--theta-min-deg", type=float, default=0.05)
    ap.add_argument(
        "--distance-cosmology",
        choices=("desi", "legacy_astropy"),
        default="desi",
        help="Redshift-to-distance mapping. Production default is cosmoprimo.fiducial.DESI; legacy_astropy reproduces the earlier H0=67.4, Om0=0.315 mapping.",
    )
    ap.add_argument("--nthreads", type=int, default=max(1, os.cpu_count() or 1))
    ap.add_argument(
        "--skip-reverse",
        action="store_true",
        help="Skip the ELG->LRG sign-reversal validation to save time.",
    )
    args = ap.parse_args()

    set_distance_cosmology(args.distance_cosmology)

    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    sedges = np.asarray([float(x) for x in args.sep_edges.split(",")], dtype="f8")
    if np.any(np.diff(sedges) <= 0):
        raise ValueError("Separation edges must be strictly increasing")

    print("Reading data catalogs", flush=True)
    lrg = read_catalog(args.lrg_data, args.zmin, args.zmax)
    elg = read_catalog(args.elg_data, args.zmin, args.zmax)
    print("Reading random catalogs", flush=True)
    lrg_r = read_catalog(args.lrg_random, args.zmin, args.zmax)
    elg_r = read_catalog(args.elg_random, args.zmin, args.zmax)

    counts = {
        "LRG": int(len(lrg[2])),
        "ELG": int(len(elg[2])),
        "LRG_random": int(len(lrg_r[2])),
        "ELG_random": int(len(elg_r[2])),
    }
    print("COUNTS", json.dumps(counts), flush=True)

    print("Exact Corrfunc LRG->ELG", flush=True)
    corr, sep, xi1, xi3 = run_corr(
        lrg, elg, lrg_r, elg_r, sedges, args.mu_bins, args.nthreads, args.theta_min_deg
    )
    finite_or_raise("LRG->ELG", sep, xi1, xi3)
    corr.save(str(out / "pycorr_lrg_to_elg.npy"))

    reverse = None
    if not args.skip_reverse:
        print("Exact Corrfunc ELG->LRG sign-reversal check", flush=True)
        corr_rev, sep_rev, xi1_rev, xi3_rev = run_corr(
            elg, lrg, elg_r, lrg_r, sedges, args.mu_bins, args.nthreads, args.theta_min_deg
        )
        finite_or_raise("ELG->LRG", sep_rev, xi1_rev, xi3_rev)
        corr_rev.save(str(out / "pycorr_elg_to_lrg.npy"))
        if not np.allclose(sep, sep_rev, rtol=0.0, atol=1e-12):
            raise RuntimeError("Forward and reverse separation grids differ")
        eps = 1e-300
        reverse = {
            "dipole_max_abs_forward_plus_reverse": float(np.max(np.abs(xi1 + xi1_rev))),
            "octupole_max_abs_forward_plus_reverse": float(np.max(np.abs(xi3 + xi3_rev))),
            "dipole_relative_sign_residual": float(
                np.max(np.abs(xi1 + xi1_rev)) / max(np.max(np.abs(xi1)), eps)
            ),
            "octupole_relative_sign_residual": float(
                np.max(np.abs(xi3 + xi3_rev)) / max(np.max(np.abs(xi3)), eps)
            ),
        }
        np.savetxt(
            out / "lrg_elg_exact_forward_reverse.csv",
            np.column_stack([sep, xi1, xi1_rev, xi3, xi3_rev]),
            delimiter=",",
            header="s_Mpc_over_h,xi1_LRG_to_ELG,xi1_ELG_to_LRG,xi3_LRG_to_ELG,xi3_ELG_to_LRG",
            comments="",
        )
        print("SIGN_REVERSAL", json.dumps(reverse), flush=True)

    np.savetxt(
        out / "lrg_elg_exact_odd_multipoles.csv",
        np.column_stack([sep, xi1, xi3]),
        delimiter=",",
        header="s_Mpc_over_h,xi1_LRG_to_ELG,xi3_LRG_to_ELG",
        comments="",
    )

    try:
        import pycorr
        pycorr_version = getattr(pycorr, "__version__", "unknown")
    except Exception:
        pycorr_version = "unknown"
    try:
        import Corrfunc
        corrfunc_version = getattr(Corrfunc, "__version__", "unknown")
    except Exception:
        corrfunc_version = "unknown"
    try:
        import cosmoprimo
        cosmoprimo_version = getattr(cosmoprimo, "__version__", "unknown")
    except Exception:
        cosmoprimo_version = None

    summary = {
        "scope": "Exact-pair genuine DESI DR1 LRGxELG odd-multipole data vector; significance requires mock covariance.",
        "pair_counting": "pycorr with Corrfunc, no Monte-Carlo pair subsampling",
        "estimator": "cross Landy-Szalay in (s,mu), projected to ell=1 and ell=3",
        "orientation": "LRG->ELG",
        "los": "midpoint",
        "distance_cosmology": args.distance_cosmology,
        "distance_units": "Mpc/h",
        "z_range": [args.zmin, args.zmax],
        "object_weighted_z_proxy": weighted_zeff(lrg, elg),
        "counts": counts,
        "random_files": {
            "LRG": [str(Path(x)) for x in args.lrg_random],
            "ELG": [str(Path(x)) for x in args.elg_random],
        },
        "separation_edges_Mpc_over_h": sedges.tolist(),
        "mu_bins": int(args.mu_bins),
        "theta_min_deg": float(args.theta_min_deg),
        "nthreads": int(args.nthreads),
        "weights": "WEIGHT * WEIGHT_FKP for data and randoms",
        "pycorr_version": pycorr_version,
        "corrfunc_version": corrfunc_version,
        "cosmoprimo_version": cosmoprimo_version,
        "sign_reversal": reverse,
        "guardrail": (
            "Do not quote a physical significance from this file alone. "
            "Use an identically processed mock ensemble for covariance and a frozen "
            "standard-odd plus wake template model for inference."
        ),
    }
    (out / "summary_exact.json").write_text(json.dumps(summary, indent=2) + "\n")
    print("EXACT_SUMMARY", json.dumps(summary, indent=2), flush=True)


if __name__ == "__main__":
    main()
