#!/usr/bin/env python3
"""Independent E17B pure-stdlib replay of archived native CLASS transfer arrays.

No import of E17A/E17B runner, NumPy, CLASS, FITS, survey data or physically
uncalibrated bispectrum model. Native arrays were generated by original E17B CLASS.
"""
from __future__ import annotations
import argparse
import bisect
import hashlib
import json
import math
import os
import tempfile
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
PRE=ROOT/"source_data/eboss_dr16_a03_e17b_native_transfer_k_resolution_prereg_2026-09-27.json"
OUT=ROOT/"eboss_workspace/a03_physics_source/e17b_native_transfer"
ARCH=ROOT/"source_data/eboss_dr16_a03_e17_archived_CI_2026_09_27"
STATES=("FD","plus","minus")
ZS=(.945,.95,.955)
FIELDS=("Pcb","theta","dcb")

def ck(a,s):
    if not a:raise RuntimeError("E17B_INDEPENDENT_FAIL_CLOSED: "+s)
def sha(x):return hashlib.sha256(x).hexdigest()
def blob(x):return hashlib.sha1(b"blob "+str(len(x)).encode()+b"\0"+x).hexdigest()
def scaled(a,b,floor):return abs(a-b)/max(abs(a),abs(b),floor)
def interp(ks,arr,x):
    i=bisect.bisect_right(ks,x)
    ck(i>0 and i<len(ks),"native CLASS leg outside measured k grid")
    lo=ks[i-1];hi=ks[i]
    ck(hi>lo,"native CLASS k monotonicity lost")
    return arr[i-1]+(x-lo)/(hi-lo)*(arr[i]-arr[i-1])
def write_new(path,obj):
    raw=(json.dumps(obj,indent=2,allow_nan=False)+"\n").encode()
    path.parent.mkdir(parents=True,exist_ok=True)
    if path.exists():ck(path.read_bytes()==raw,"independent cert output collision")
    else:
        with tempfile.NamedTemporaryFile(dir=path.parent,prefix=".e17b_ind_",delete=False) as f:
            t=Path(f.name);f.write(raw);f.flush();os.fsync(f.fileno())
        try:os.link(t,path)
        finally:t.unlink(missing_ok=True)
    print("E17B_INDEPENDENT_CERTIFICATE",path,"SHA256",sha(raw),flush=True)

def run(out):
    p=json.loads(PRE.read_bytes());pins=p["parent"]
    ck(blob(PRE.read_bytes())=="d0389e336de9e9964cade589fc17594a595f2e17"
       and p["absolute_STOP"]["no_observed_odd_read"],"prospective prereg altered")
    original_joint=out/"e17b_original_joint_native_CLASS_transfer_resolution.json"
    joint=json.loads(original_joint.read_bytes())
    ck(joint["prospective_protocol_git_blob"]=="d0389e336de9e9964cade589fc17594a595f2e17"
       and joint["physical_finite_K_bispectrum"]=="BLOCKED","joint source physical STOP altered")
    E17A=json.loads((ARCH/"e17_original_joint_three_state_CLASS_both_short_legs_source_only.json").read_bytes())
    ck(sha((ARCH/"e17_original_joint_three_state_CLASS_both_short_legs_source_only.json").read_bytes())==
       pins["E17A_original_joint_sha256"] and E17A["geometry_count"]==576,
       "E17A original SHA or frozen geometry invalid")
    qa={"states":0,"independent_native_scalar_interpolation_evaluations":0,
        "original_baseline_leg_z_field_comparisons":0,
        "max_native_transfer_replay_scaled_gap":0.,
        "max_original_qa_metric_replay_abs_gap":0.,
        "native_node_counts_by_state":{},"max_original_triangle_coordinate_difference":0.}
    for st in STATES:
        path=out/("e17b_refined_native_CLASS_"+st+".json")
        raw=path.read_bytes()
        ck(sha(raw)==joint["state_reports"][st]["sha256"],"E17B original state report SHA altered")
        a=json.loads(raw)
        ck(a["state"]==st and not a["observed_odd_read"] and
           a["physical_finite_K_B_xi_SNR_significance"] is None,
           "source-only report/observed STOP changed")
        oldpath=ARCH/("e17_original_both_legs_"+st+".json")
        ck(sha(oldpath.read_bytes())==pins["E17A_original_per_state_sha256"][st],
           "E17A original state SHA changed")
        old=json.loads(oldpath.read_bytes())
        rows=old["rows_original_576_geometry_three_z_two_legs"]
        ck(len(rows)==576,"original frozen 576 triangles changed")
        legs=[row["k"+str(i)+"_h_Mpc"] for row in rows for i in (1,2)]
        baseline={str(z):{f:[] for f in FIELDS} for z in ZS}
        for z in ZS:
            for row in rows:
                for i in (1,2):
                    r=row["z_nodes"][str(z)]["leg"+str(i)]
                    baseline[str(z)]["Pcb"].append(r["P_cb_CLASS_Mpc3"])
                    baseline[str(z)]["theta"].append(r["theta_rel_DIRECT_vTk_per_R_Mpc_inv"])
                    baseline[str(z)]["dcb"].append(r["delta_cb_Newtonian_per_R"])
                    qa["original_baseline_leg_z_field_comparisons"]+=3
        data=a["native_CLASS_evaluations_by_fixed_tier"]
        interpolated={}
        for tier in ("tier_high","tier_ultra"):
            x=data[tier]
            ks=x["native_grid"]["k_h_Mpc"]
            n=x["native_grid"]["N"]
            ck(n==len(ks) and all(ks[i]<ks[i+1] for i in range(n-1)) and
               ks[0]<min(legs) and ks[-1]>max(legs),"native CLASS bracketing/grid mismatch")
            interpolated[tier]={}
            for z in ZS:
                node=x["z_nodes"][str(z)]
                raw=node["native"]
                ck(all(len(raw[k])==n for k in ("t_ncdm[0]","t_cdm","d_b","d_cdm")),
                   "one native CLASS transfer field missing")
                samples=node["actual_leg_samples"]
                theta=[a-b for a,b in zip(raw["t_ncdm[0]"],raw["t_cdm"])]
                dcb=[(a["omega_b"]*b+a["omega_cdm"]*c)/(a["omega_b"]+a["omega_cdm"])
                     for b,c in zip(raw["d_b"],raw["d_cdm"])]
                samples_ref={}
                for fld,series in (("theta",theta),("dcb",dcb)):
                    values=[interp(ks,series,k) for k in legs]
                    ck(len(values)==len(samples[fld])==1152,"leg sample dimension mismatch")
                    for v,oldval in zip(values,samples[fld]):
                        gap=scaled(v,oldval,1e-30)
                        qa["max_native_transfer_replay_scaled_gap"]=max(
                            qa["max_native_transfer_replay_scaled_gap"],gap)
                        ck(gap<p["prereg_engineering_diagnostics_NOT_physical_error_budget"][
                            "independent_native_array_replay_scaled_tolerance"],
                            "independent native transfer interpolation failed")
                        qa["independent_native_scalar_interpolation_evaluations"]+=1
                    samples_ref[fld]=values
                pc=samples["Pcb"]
                ck(len(pc)==1152 and all(math.isfinite(v) and v>0 for v in pc),
                   "fresh CLASS per-leg Pcb missing")
                samples_ref["Pcb"]=pc
                interpolated[tier][str(z)]=samples_ref
        counts={tier:data[tier]["native_grid"]["N"] for tier in ("tier_high","tier_ultra")}
        ck(81<counts["tier_high"]<counts["tier_ultra"],
           "predeclared native k-resolution hierarchy did not materialize")
        qa["native_node_counts_by_state"][st]=counts
        anchors=json.loads((ROOT/"source_data/eboss_dr16_a03_e14_archived_CI_2026_09_27"/("e14_short_Pcb_"+st+".json")).read_bytes())["CLASS_Pcb_short_per_state_Mpc3"]
        anchor=max(abs(data[tier]["E14_three_short_k_Pcb_Mpc3"][k]-anchors[k])/anchors[k]
                   for tier in ("tier_high","tier_ultra") for k in ("0.05","0.075","0.1"))
        ck(abs(anchor-a["QA"]["max_original_anchor_Pcb_relative_gap"])<1e-13,
           "refined E14 original anchor QA not independently reproduced")
        for fld in FIELDS:
            entry=a["convergence_diagnostics"][fld]
            floor=entry["scale_floor_for_near_zero"]
            for pair,left,right in (("baseline_vs_ultra",baseline,interpolated["tier_ultra"]),
                                    ("high_vs_ultra",interpolated["tier_high"],interpolated["tier_ultra"])):
                gaps=[]
                for z in ZS:
                    za=left[str(z)][fld];zb=right[str(z)][fld]
                    ck(len(za)==len(zb)==1152,"one fixed-geometry leg field missing")
                    gaps.extend(scaled(v,w,floor) for v,w in zip(za,zb))
                ck(len(gaps)==3456,"original three-z two-leg layout changed")
                got=max(gaps);expected=entry[pair]["max_scaled_gap"]
                err=abs(got-expected)
                qa["max_original_qa_metric_replay_abs_gap"]=max(
                    qa["max_original_qa_metric_replay_abs_gap"],err)
                ck(err<=1e-12*max(1.,abs(got),abs(expected)),
                   "original/native quantitative resolution summary mismatch")
        qa["states"]+=1
    ck(qa["states"]==3 and qa["independent_native_scalar_interpolation_evaluations"]==41472
       and qa["original_baseline_leg_z_field_comparisons"]==31104,
       "missing independently audited original full two-leg sample coverage")
    result={"date":"2026-09-27",
        "status":"E17B_INDEPENDENT_FULL_NATIVE_ARRAY_TWO_TIER_THREE_STATE_SCALAR_REPLAY_PASS_NO_PHYSICAL_B",
        "preregistered_E17B_git_blob":"d0389e336de9e9964cade589fc17594a595f2e17",
        "original_joint_sha256":sha(original_joint.read_bytes()),
        "original_E17A_joint_sha256":pins["E17A_original_joint_sha256"],
        "independent_method":"Completely separate standard-library scalar brackets and interpolation from archived actual refined CLASS native transfer arrays; no E17B runner import or fresh independent CLASS rerun. Original E17A already has independent fresh CLASS numerical replay.",
        "QA":qa,"original_E17B_engineering_candidate":joint["all_three_state_qa_candidate"],
        "physics_stop":"Full finite-K retarded halo/tracer B and eBOSS 3pt observable BLOCKED",
        "observed_odd_read":False,"new_mock_catalogue_download_science_seed_cut":False,
        "main_untouched_PR_draft":True}
    write_new(out/"e17b_independent_native_array_scalar_replay.json",result)
    print("E17B_INDEPENDENT_ALL_NATIVE_SCALAR_REPLAY_PASS",qa,flush=True)

if __name__=="__main__":
    ar=argparse.ArgumentParser()
    ar.add_argument("--output-dir",type=Path,default=OUT)
    a=ar.parse_args();run(a.output_dir)
